### ISSUE TITLE
Unable to export targets. e[0].replace is not a function.

### ISSUE THREAD

**Issue by Vaneko** [fcamarlinghi/expresso#35] opened 2024-06-12 21:59 UTC
Hi, getting this weird error when I press on "export selected targets". Using latest version 0.6.5 and Photoshop 25.9.0

![1111](https://github.com/fcamarlinghi/expresso/assets/29803502/32f07dcb-b10c-46d4-93ef-1a4458c8f135)

**Comment by fcamarlinghi** [comment] 2024-06-13 08:12
Hi @Vaneko, could you please share your logs? You can find them in:

- Windows: `C:\Users\<username>\AppData\Roaming\Expresso\Exporter\logs`
- Mac: `/Users/<username>/Library/Logs/Expresso/Exporter`

**Comment by Vaneko** [comment] 2024-06-13 17:19
[exporter-main.log](https://github.com/user-attachments/files/15826196/exporter-main.log)

**Comment by fcamarlinghi** [comment] 2024-06-14 07:27
Thanks! I think the problem is that no layer has been selected to export in "_C" and "_R". Disabling these export targets (or updating them to use a valid layer) should fix the problem.

Looking at the logs it seems you're using version 0.6.3 of the plugin:

```
08:57:51.812 [Extension] [INFO] Extension Expresso Exporter 0.6.3 initialized. 
```

More recent versions should display a more descriptive error message in similar situations. Could you please also try updating to the latest version (0.6.5)?

**Comment by Vaneko** [comment] 2024-06-15 07:57
Hey, thanks for your reply. I am already using 0.6.5 since I downloaded the latest version. Don't know why the log file says a previous version. I will check that

**Comment by fcamarlinghi** [comment] 2024-06-25 12:12
Closing the issue for now. Please feel free to reopen it if needed!

**Closed as completed by fcamarlinghi** 2024-06-25 12:12 UTC
